version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: creco-db
    ports:
      - 55555:3306
    volumes:
      - "./mysql/scripts/:/docker-entrypoint-initdb.d/"
      - "./mysql/my.cnf:/etc/my.cnf"
      - "./mysql/data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: "hello"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - creco-network
networks:
  creco-network: